version: '3.1'

services:
  mysql:
    image: mysql:8.0.31
    command: --authentication-policy=sha256_password
    environment:
      MYSQL_DATABASE: "career-symfony"
      MYSQL_USER: "rxijian"
      MYSQL_PASSWORD: "Fl4IP81iXy1L1NrzCGqroXTDio66ttrGFunqaPXz"
      MYSQL_ROOT_PASSWORD: "wS6nh9VeYp79Vd1RQueoKWkKYdlsLIBKbztGtTEE"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: localhost
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: "wS6nh9VeYp79Vd1RQueoKWkKYdlsLIBKbztGtTEE"
    restart: always
    ports:
      - 8081:80

volumes:
  mysql-volume: